### ISSUE TITLE
search engine indexing must be not allowed

### ISSUE THREAD

**Issue by muatik** [muatik/flask-profiler#20]
a robot.txt file may be created to prevent search engines from indexing flask profiler's dashboard because it most probably has confidential information.

**Comment by TigerApps** [comment]
With auth added, this issue can be closed too?

**Comment by muatik** [comment]
not necessarily because there may be some cases in which auth is disabled and indexing is still not wanted.

**Comment by iurisilvio** [comment]
I don't think this must be responsible for a robots.txt file. The application probably already have a robots file.

For index.html, you can just set a meta tag:

```html
<meta name="robots" content="noindex, nofollow">
```

For JSON resources, it is obviously not possible to add an HTML tag. Most crawlers respect the `X-Robots-Tag`.

I sent a pull request (#26) with these changes.

**Comment by muatik** [comment]
your solution looks like to me sufficient for this issue. :+1:
