### ISSUE TITLE
Allow deletion of profiling from UI and/or profiling session

### ISSUE THREAD

**Issue by divyenduz** [muatik/flask-profiler#32]
Are you considering adding some functionality to start a profiling session. As information marked without it is difficult to process ? 

Also, one easy way of doing that would be to have buttons like :-
1. delete all data (to start over)
2. Save and delete all data (to save a session or all data so far and start over)

If you guys agree on this, I can start working on a PR for the same :)

Thanks

**Comment by divyenduz** [comment]
I know it is possible to delete / copy the DB manually to achieve all this but I think it would be a good to have feature on UI

**Comment by muatik** [comment]
Hi @divyenduz 

Your recommendations are really cool. It would be great to have a "dump current database" and "delete all data" button on a page, maybe a settings page?

You are free to make any changes as you wish :)

**Comment by muatik** [comment]
hi @divyenduz, are you still interested in this issue and its implementation?

**Comment by divyenduz** [comment]
@muatik : Thanks for notifying. I am interested but never got a change. I hope you can wait for 2-3 weekends before closing this one ?

**Comment by muatik** [comment]
yeap, that's ok.

**Comment by divyenduz** [comment]
@muatik : Hey, I started working on this, however, I have a few (naive) concerns. 

1. The example app.py import did not work for me
I got an import error in that case, I had include the parent path (code below) to make it work. Am I doing something wrong ?
```
import sys
sys.path.insert(0,'..')
```

2. I started off with the UI (looks like the image below)
![settings](https://cloud.githubusercontent.com/assets/746482/15247294/f192c71e-1930-11e6-915e-18ecb4b5f01d.png)

2.1 Let's discuss a rough UI structure for settings page or the screenshot looks fine to you ? I can complete the functionality and we can tinker the UI later also.

2.2 How do you make changes to the JS file ? It looks like a minfied file to me (see screenshot), do you use a build process for it or are you on windows (could be missing line ends) ?

![main](https://cloud.githubusercontent.com/assets/746482/15247375/6c694116-1931-11e6-9b34-9ad2a3e22174.png)

[File link for reference](https://github.com/muatik/flask-profiler/blob/master/flask_profiler/static/dist/js/main.js)

Once I am clear on these, It should not take me much time to get this done.

Thanks,

**Comment by muatik** [comment]
@divyenduz great that you started contribution.

1) actually you should not change the example/app.py since as its name suggest, it is an example. it is intended to be run with the flask-profiler install via pip. but doing your development, it is ok, just do not commit changes in it :)

2.1) your settings ui looks like enough to me, since we have only two action/button. we can move on with it.

2.2) indeed it is minified. @xorxor was involved in the client side code. most probably he used a build process. @xorxor could you give brief information on it?

3) yes you can.

**Comment by divyenduz** [comment]
@muatik Thanks for the information. 
No news on the front end build description yet. 

I will continue by making a separate JS file for now until I am given heads up on the JS build system.

**Comment by divyenduz** [comment]
@muatik : Should I send a PR with external JS, I added another file to get the functionality done ? No news on the JS build system yet. 

I am comfortable for @xorxor to reply and then send PR later. Let me know. :)

**Comment by muatik** [comment]
@divyenduz I think, at this point, external files are not obstacles. so, you can send PR without waiting. maybe @xorxor can edit/merge the files later.

**Comment by divyenduz** [comment]
@muatik : Thanks, I will sent the PR soon then. Thanks.

**Comment by divyenduz** [comment]
@muatik : It took me long but now we have something concrete to discuss. 
Your opinion on this https://github.com/muatik/flask-profiler/pull/41
