### ISSUE TITLE
flask-profiler work in production mode?

### ISSUE THREAD

**Issue by havok2063** [muatik/flask-profiler#38]
Does the flask-profiler only work in debug mode?  While this is great for debugging, I'd like to collect statistics while users are navigating my Flask app in a real production environment.  Is this possible?  If so, can you provide an example of the config info that needs to be set?

**Comment by muatik** [comment]
It can work regardless of what the debug mode is. Please have a look at quick start examples: https://github.com/muatik/flask-profiler#quick-start

You can turn on/off it using the `enabled` directive as follows. 

If debug mode is on, then the flask profiler is on.
```python
app.config["flask_profiler"] = {
    "enabled": app.config["DEBUG"]
}
```

Flask-profiler is always on:
```python
app.config["flask_profiler"] = {
    "enabled": True
}
```

**Comment by muatik** [comment]
and if you want to use it in a production environment, do not forget to turn basic authentication on so that only people know username and password can access to flask-profiler.

```python
app.config["flask_profiler"] = {
    "enabled": True
    "basicAuth":{
        "enabled": True,
        "username": "admin",
        "password": "admin"
    }
}
```

**Comment by havok2063** [comment]
Ok.  That makes sense.  I did read the quickstart, but it wasn't clear about debug vs production.  And I only say 
```
    app.config["flask_profiler"] = {
        "enabled": app.config["DEBUG"],
    }
```

**Comment by divyenduz** [comment]
The next release will also have a feature to do sampling in production, making flask-profiler lean and more useful for production workloads. Refer to https://github.com/muatik/flask-profiler/issues/44 for details.
