### ISSUE TITLE
changing url route of flask-profiler

### ISSUE THREAD

**Issue by havok2063** [muatik/flask-profiler#43]
How can we modify the url route for the flask-profiler?  Currently it automatically routes to the main, e.g.

`localhost:5000/flask-profiler/
`

This is fine for debug mode or for production mode where you are not behind a subdomain on a larger server.  How can I set the url route for flask-profiler to be behind a subdomain so it works in production mode? E.g. my webapp site is at

`www.domainname.com/myapp/
`

and I would like to access the flask-profiler at 

`www.domainname.come/myapp/flask-profiler/
`

Both of these

```
www.domainname.come/myapp/flask-profiler/
www.domainname.com/flask-profiler/
```

fail and do not recognize the name.  This question is related to #38.

My config for flask-profiler is configured for production mode

```
    # Setup the profile configuration
    app.config["flask_profiler"] = {
        "enabled": True,
        "storage": {
            "engine": "sqlite"
        },
        "basicAuth": {
            "enabled": True,
            "username": "admin",
            "password": "admin"
        }
    }
```

Has anyone actually successfully used this in a production environment and not in debug mode?

**Comment by savakarv** [comment]
We have done that in our project. I am able to access flask_profiler in a link http://example.com/project-name/flask-profiler/

We were able to achieve this by setting WSGIScriptAlias in httpd.conf file (service is running inside Tomcat).
WSGIScriptAlias /project-name "/project/path/project-name-rest.wsgi"

**Comment by muatik** [comment]
There is an option to set flask-profiler's url, however it isn't documented yet. https://github.com/muatik/flask-profiler/blob/master/flask_profiler/flask_profiler.py#L153

```python
app.config["flask_profiler"] = {
        "endpointRoot": "secret-flask-profiler"
}
```
This directive's defaut value is `flask-profiler`.

I, or somebody, need to should be documented in README.md
