### ISSUE TITLE
Optimizing for production profiling like XHGui 

### ISSUE THREAD

**Issue by divyenduz** [muatik/flask-profiler#44]
Is there a feature where we can limit the number of samples probabilistic and use profile in production with huge load ?

If such a feature is not present, we can create one like :- 

This is done in one of php profilers named `XHGui` | https://github.com/perftools/xhgui

`The following example configures XHGui to profile 1 in 100 requests, excluding requests with the /blog URL path:`

**Comment by muatik** [comment]
currently, there is not such a feature. but it would be a useful feature.

**Comment by divyenduz** [comment]
I think I can take this up and line up a PR ? 
Should I go ahead ?

**Comment by muatik** [comment]
that sounds great :) but first, should we discuss a little how the feature will be? 

if we choose 1 in 100 in an arbitrary way, or random, then the summary section may have strange results. there may be a setting directive to tune the ratio, in some apps it would be 1/10, or 1/1M?

**Comment by divyenduz** [comment]
Yes, a discussion is much needed on this :)

So, broadly when we take random sample with 1/100 probability, we rely on math to get us 1% of the sample set | https://en.wikipedia.org/wiki/Normal_distribution

Which is why this works well for `XHGui` and this is normally suggested when you ask questions about this topic | http://stackoverflow.com/questions/12364622/php-how-to-run-sampling-profiler-in-production

Do you have another approach in mind for getting a sample set ?

Thanks

**Comment by muatik** [comment]
okay, let's go with this.

**Comment by divyenduz** [comment]
Cool, I will start soon. Do you have another release date in mind, I will try to cover this before that ?

**Comment by muatik** [comment]
nope, actually there isn't a planned release. so, feel free while working on this; as soon as possible this feature is completed a new release can be presented.

**Comment by divyenduz** [comment]
Thanks, I will start this weekend, hopefully. :+1:

**Comment by divyenduz** [comment]
The initial PR is prepared. Let's discuss the implementation when you get a chance ?

**Comment by divyenduz** [comment]
@muatik : With https://github.com/muatik/flask-profiler/pull/45 merged, I think this issue can be closed. Planning a release anytime soon ?

Thanks,
