### ISSUE TITLE
Importing database dump

### ISSUE THREAD

**Issue by divyenduz** [muatik/flask-profiler#50]
The process of dumping database was covered in https://github.com/muatik/flask-profiler/issues/32 wherein we take the dump in JSON format. 

How about an option to take a file and put it back into the DB i.e. importing of a dump.

Let me know your thoughts on this. Thanks

**Comment by muatik** [comment]
we had better think about how much importing database would be useful and required. we should keep the balance between functionality and simplicity. if this is really a must or at least nice-to-have feature, yes we can implement.

**Comment by divyenduz** [comment]
My idea of dump was that the user should be able to profile a feature and save related information before deleting the DB and start to profile some other feature. 

The idea of importing is not actually putting it into the DB but reading the JSON and putting it in memory for us to use the flask profiler view to navigate through that JSON.

So, this function can be as simple as a import button that loads a file in the dashboard / filtering tabs or similar functionality with some other UI. The idea is to make the JSON file readable by flask profiler via some sort of import
