### ISSUE TITLE
Feature: time series for request elapsed time for one route

### ISSUE THREAD

**Issue by divyenduz** [muatik/flask-profiler#56]
I think this will be a good addition, I am expecting the following in MVP:

1. This will help us measure the impact of deployments in a much easier manner. 
2. This will open once we click a URL

@muatik : What is your opinion on this ?

Regards

**Comment by muatik** [comment]
Does it mean that when a user clicks a route, he or she will be able to see a time series line chart for that route for a given data range?

**Comment by divyenduz** [comment]
Yes, something like this. So, say I saw that one of my endpoints is taking time, I make a deployment to fix this. This graph will help me easily validate that the deploy has worked.

**Comment by muatik** [comment]
Yeah, this looks like a useful feature. We can elaborate a little deeper.

Let's go through a scenario. A user clicks the route, `/api/products/`, on the interface. To construct a chart view, the UI needs to fetch historic data of `/api/products/`. 

However, this route might be called with different query parameters, such as `/api/products/?q=foo` and `/api/products/?q=bar&r=1` So should this fetching operation obtain historic data regardless of query parameters or it should fetch historic data matching the current route's query parameters?

Either way, an API to fetch time series data is required. We should consider creating necessary database index if necessary.

**Comment by divyenduz** [comment]
I think both options should be there, when a user clicks on a url, only that should be specified but there should be an option to ignore query parameters.

The first step before building this though would be to reverse engineer the JS. 

How does this sound ? I will make detailed plans, database and API requirements for this if both of us are on the same page.

Thanks

**Comment by muatik** [comment]
I am okay, let's take action.

**Comment by divyenduz** [comment]
Awesome, I will draft something substantial in some time. 

Thanks
