### ISSUE TITLE
Is there a way to profiling of sqlalchemy query calls  in this tool

### ISSUE THREAD

**Issue by PankajWorks** [muatik/flask-profiler#57]
Thanks for this tool, I have used the tool and its great to profile api calls. Is there a way in which this tool can be extended to profile sqlalchemy calls

**Comment by muatik** [comment]
you are welcomed @PankajWorks 

I think profiling sqlalchemy is out of scope of this project.  Flask-profiler is designed to do one thing, and do it well. You had better look for another tool for that job? For instance, after googling, I found this: http://sqltap.inconshreveable.com/ it might work for you.
