### ISSUE TITLE
Image asset being counted on each page

### ISSUE THREAD

**Issue by josiahtillman** [muatik/flask-profiler#59]
Whenever we load one of our pages, our logo (located at /static/assets/img/logo.png) is being counted in the flask-profiler as a GET with a name of "/static/<path:filename>" and is throwing off our Method distribution graph. 

Is there a way to remove this or make flask-profiler ignore this?

![screen shot 2017-02-15 at 2 24 22 pm](https://cloud.githubusercontent.com/assets/12627410/22994247/dd566e6e-f38b-11e6-8186-e7cbf1190d5b.png)

**Comment by muatik** [comment]
Currently, there is no way to ignore a specific request. However, I think the ability to ignore routes specified with either regex pattern in configurations or a decorator is necessary. Giving a regex pattern for ignoring in configuration, I guess, is simpler.

```python
app.config["flask_profiler"] = {
    "enabled": app.config["DEBUG"],
    "storage": {
        "engine": "sqlite"
    },
    "basicAuth":{
        "enabled": True,
        "username": "admin",
        "password": "admin"
    },
    "ignore": [
        "/static/*"
    ]
}
```

**Comment by muatik** [comment]
@josiahtillman could you please try the implementation?
Here is an example in which the router shown below will not be tracked by flask-profiler.

```python
app.config["flask_profiler"] = {
    ...
    "ignore": [
        "/static/*",
        "/secrets/password/"
    ]
    ...
}



@app.route('/static/photo/', methods=['GET'])
def getPhoto():
    return "your photo"

```

**Comment by josiahtillman** [comment]
@muatik I inserted 
`    "ignore": [
        "/static/*"
    ]`
but it is still showing up. I also tried this:
`    "ignore": [
        "/static/<path:filename>"
    ]`
but no luck. The weird thing is, we aren't using a method to get the image, it is simply inserted through our html, yet the flask-profiler is logging it. Here is what our logo's code looks like: 
`<img src="/static/assets/img/tinker_logo.png" style="height:35px">`

I'm thinking it might be something else in the static folder that is triggering the flask-profiler. We also have a couple of javascript and css files in there-- would those trigger it? Would there be a different way to ignore those?

**Comment by muatik** [comment]
Have you tried it after pulling flask profiler directly GitHub? Because it
is not available in pip repo.

You can install flask profiler via pip install gitgubUrl

**Comment by josiahtillman** [comment]
Ahh ok-- Just installed it directly thru GitHub and it works, except that using the "{}" instead of "{0}" is causing errors. Could possibly change this on lines 89 and 91 of flask_profiler.py?
`def measure(f, name, method, context=None):
    logger.debug("{0} is being processed.".format(name))
    if is_ignored(name, CONF):
        logger.debug("{0} is ignored.".format(name))
`

**Comment by muatik** [comment]
I've made the changes and bumped version to 1.4.  Now you can also install it via `pip install`
