### ISSUE TITLE
unable to open database file on production

### ISSUE THREAD

**Issue by veken1199** [muatik/flask-profiler#64]
I am having issue accessing the database file on Linux production server. I know the problem is associated with permission given to apache user, however, nothing seems to work. it only works when I run application using sudo. Any ideas what might be the reason ?

**Comment by muatik** [comment]
Most probably the database file(sqlite in this case) is now owned by the user who also runs the apache server. In other words, the user does not have write permission on it. 

When you run it as sudo, the sudoer user will have the write permission. So it will work.

You can give the write permission for your apache user but I suggest using mysql/postgresql or mongodb instead.
