### ISSUE TITLE
cannot import name 'measure'

### ISSUE THREAD

**Issue by sibeliusseraphini** [muatik/flask-profiler#8]
cannot import name 'measure'

**Comment by muatik** [comment]
could you please paste the code you were trying to run or it was the code shown as the sample in readme file?

**Comment by sibeliusseraphini** [comment]
I've just installed using pip install, put the code based on the sample code in README.md, and I've received this import error

**Comment by muatik** [comment]
It seems that this issue was related to python3 because I tried with python3 and got the same issue. Now this project supports python3 too, tested with python 3.4 and python 3.5

**Comment by sibeliusseraphini** [comment]
ok, thanks
