### ISSUE TITLE
class sql_alchemy some method not implemented

### ISSUE THREAD

**Issue by huangxiaohen2738** [muatik/flask-profiler#86]
In Class Sqlalchemy,
 
the method getMethodDistribution and getTimeseries are not implemeted

**Comment by bochaga-masaval** [comment]
Same issue here

**Comment by huangxiaohen2738** [comment]
@bochaga-masaval   Many methods are not implemented。 I rewrite it with flask-sqlalchemy(MySQL)

**Comment by bryangaikwad** [comment]
@huangxiaohen2738  How did you rewrite it with flask-sqlalchemy?
Following is my current flask_profiler config:
app.config["flask_profiler"] = {
    "storage": {
        "engine": "sqlalchemy",
        "db_url": app.config['SQLALCHEMY_DATABASE_URI']
    },
    "ignore": [
        "^/static/.*"
    ]
}

**Comment by huangxiaohen2738** [comment]
> @huangxiaohen2738 How did you rewrite it with flask-sqlalchemy?
> Following is my current flask_profiler config:
> app.config["flask_profiler"] = {
> "storage": {
> "engine": "sqlalchemy",
> "db_url": app.config['SQLALCHEMY_DATABASE_URI']
> },
> "ignore": [
> "^/static/.*"
> ]
> }
I write a new project by myself
