### ISSUE TITLE
Pypi version is still pointing to version 1.7 though its version is saying 1.8

### ISSUE THREAD

**Issue by anandtripathi5** [muatik/flask-profiler#92]

**Comment by anandtripathi5** [comment]
@muatik please have a look on this, I have sent a mail to you also regarding this.

**Comment by muatik** [comment]
I'll make a quick deployment to pypi. but deployment to pypi should be automated and can be done in travis.ci. https://docs.travis-ci.com/user/deployment/pypi/ I will work on it.

**Comment by anandtripathi5** [comment]
Yeah, thanks

**Comment by amarvin** [comment]
Pypi shows latest as v1.8.1, so this can be closed.
